import type { ExerciseIconManifestEntry } from './types'

/**
 * Authored source of truth for bundled exercise artwork.
 *
 * Covers the ten Bold Pose pilot exercises plus every built-in popular exercise.
 * Run `pnpm generate:exercise-icons` after changing it.
 */
export const exerciseIconManifest = [
  {
    key: 'barbell-bench-press',
    title: 'Bench Press',
    component: 'BenchPressIcon',
    aliases: ['Bench Press', 'Barbell Bench Press'],
    poseFamily: 'horizontal-press',
    equipment: ['barbell', 'bench'],
    muscles: ['chest'],
  },
  {
    key: 'barbell-row',
    title: 'Barbell Row',
    component: 'BarbellRowIcon',
    aliases: ['Barbell Row', 'Bent-over Barbell Row'],
    poseFamily: 'hinged-pull',
    equipment: ['barbell'],
    muscles: ['back'],
  },
  {
    key: 'barbell-deadlift',
    title: 'Deadlift',
    component: 'DeadliftIcon',
    aliases: ['Deadlift', 'Barbell Deadlift', 'Conventional Deadlift'],
    poseFamily: 'hinge',
    equipment: ['barbell'],
    muscles: ['back', 'legs'],
  },
  {
    key: 'barbell-back-squat',
    title: 'Squat',
    component: 'SquatIcon',
    aliases: ['Squat', 'Barbell Squat', 'Back Squat', 'Barbell Back Squat'],
    poseFamily: 'squat',
    equipment: ['barbell'],
    muscles: ['legs'],
  },
  {
    key: 'barbell-overhead-press',
    title: 'Overhead Press',
    component: 'OverheadPressIcon',
    aliases: ['Overhead Press', 'Barbell Overhead Press', 'Strict Press', 'Military Press'],
    poseFamily: 'vertical-press',
    equipment: ['barbell'],
    muscles: ['shoulders'],
  },
  {
    key: 'dumbbell-curl',
    title: 'Dumbbell Curl',
    component: 'DumbbellCurlIcon',
    aliases: ['Dumbbell Curl', 'Dumbbell Biceps Curl', 'Biceps Curl'],
    poseFamily: 'standing-curl',
    equipment: ['dumbbell'],
    muscles: ['arms'],
  },
  {
    key: 'bodyweight-plank',
    title: 'Plank',
    component: 'PlankIcon',
    aliases: ['Plank', 'Forearm Plank'],
    poseFamily: 'prone-brace',
    equipment: ['bodyweight'],
    muscles: ['core'],
  },
  {
    key: 'kettlebell-swing',
    title: 'Kettlebell Swing',
    component: 'KettlebellSwingIcon',
    aliases: ['Kettlebell Swing', 'Two-handed Kettlebell Swing', 'Russian Kettlebell Swing'],
    poseFamily: 'ballistic-hinge',
    equipment: ['kettlebell'],
    muscles: ['back', 'legs'],
  },
  {
    key: 'kettlebell-goblet-squat',
    title: 'Kettlebell Goblet Squat',
    component: 'KettlebellGobletSquatIcon',
    aliases: ['Kettlebell Goblet Squat', 'Goblet Squat'],
    poseFamily: 'goblet-squat',
    equipment: ['kettlebell'],
    muscles: ['legs'],
  },
  {
    key: 'kettlebell-turkish-get-up',
    title: 'Kettlebell Turkish Get-up',
    component: 'KettlebellTurkishGetUpIcon',
    aliases: ['Kettlebell Turkish Get-up', 'Turkish Get-up'],
    poseFamily: 'ground-to-standing',
    equipment: ['kettlebell'],
    muscles: ['core', 'shoulders'],
  },
  {
    key: 'dumbbell-chest-fly',
    title: 'Chest Fly',
    component: 'DumbbellChestFlyIcon',
    aliases: ['Chest Fly'],
    poseFamily: 'supine-fly',
    equipment: ['dumbbell'],
    muscles: ['chest'],
  },
  {
    key: 'cable-crossover',
    title: 'Cable Crossover',
    component: 'CableCrossoverIcon',
    aliases: ['Cable Crossover'],
    poseFamily: 'standing-fly',
    equipment: ['cable'],
    muscles: ['chest'],
  },
  {
    key: 'cable-fly',
    title: 'Cable Fly',
    component: 'CableFlyIcon',
    aliases: ['Cable Fly'],
    poseFamily: 'standing-fly',
    equipment: ['cable'],
    muscles: ['chest'],
  },
  {
    key: 'machine-chest-press',
    title: 'Chest Press Machine',
    component: 'MachineChestPressIcon',
    aliases: ['Chest Press Machine'],
    poseFamily: 'seated-press',
    equipment: ['machine'],
    muscles: ['chest'],
  },
  {
    key: 'machine-incline-chest-press',
    title: 'Incline Chest Press Machine',
    component: 'MachineInclineChestPressIcon',
    aliases: ['Incline Chest Press Machine'],
    poseFamily: 'seated-press',
    equipment: ['machine'],
    muscles: ['chest'],
  },
  {
    key: 'machine-pec-deck',
    title: 'Pec Deck',
    component: 'MachinePecDeckIcon',
    aliases: ['Pec Deck'],
    poseFamily: 'seated-fly',
    equipment: ['machine'],
    muscles: ['chest'],
  },
  {
    key: 'smith-machine-bench-press',
    title: 'Smith Machine Bench Press',
    component: 'SmithMachineBenchPressIcon',
    aliases: ['Smith Machine Bench Press'],
    poseFamily: 'horizontal-press',
    equipment: ['machine'],
    muscles: ['chest'],
  },
  {
    key: 'smith-machine-incline-press',
    title: 'Smith Machine Incline Press',
    component: 'SmithMachineInclinePressIcon',
    aliases: ['Smith Machine Incline Press'],
    poseFamily: 'incline-press',
    equipment: ['machine'],
    muscles: ['chest'],
  },
  {
    key: 'bodyweight-beast-push-up',
    title: 'Beast Push-up',
    component: 'BodyweightBeastPushUpIcon',
    aliases: ['Beast Push-up'],
    poseFamily: 'quadruped',
    equipment: ['bodyweight'],
    muscles: ['chest'],
  },
  {
    key: 'bodyweight-clap-push-up',
    title: 'Clap Push-ups',
    component: 'BodyweightClapPushUpIcon',
    aliases: ['Clap Push-ups'],
    poseFamily: 'prone-press',
    equipment: ['bodyweight'],
    muscles: ['chest'],
  },
  {
    key: 'bodyweight-decline-push-up',
    title: 'Decline Push-ups',
    component: 'BodyweightDeclinePushUpIcon',
    aliases: ['Decline Push-ups'],
    poseFamily: 'prone-press',
    equipment: ['bodyweight'],
    muscles: ['chest'],
  },
  {
    key: 'bodyweight-diamond-push-up',
    title: 'Diamond Push-ups',
    component: 'BodyweightDiamondPushUpIcon',
    aliases: ['Diamond Push-ups'],
    poseFamily: 'prone-press',
    equipment: ['bodyweight'],
    muscles: ['chest'],
  },
  {
    key: 'bodyweight-dips',
    title: 'Dips',
    component: 'BodyweightDipsIcon',
    aliases: ['Dips'],
    poseFamily: 'support-press',
    equipment: ['bodyweight'],
    muscles: ['chest'],
  },
  {
    key: 'bodyweight-push-up',
    title: 'Push-ups',
    component: 'BodyweightPushUpIcon',
    aliases: ['Push-ups'],
    poseFamily: 'prone-press',
    equipment: ['bodyweight'],
    muscles: ['chest'],
  },
  {
    key: 'bodyweight-wide-push-up',
    title: 'Wide Push-ups',
    component: 'BodyweightWidePushUpIcon',
    aliases: ['Wide Push-ups'],
    poseFamily: 'prone-press',
    equipment: ['bodyweight'],
    muscles: ['chest'],
  },
  {
    key: 'kettlebell-dead-clean',
    title: 'Kettlebell Dead Clean',
    component: 'KettlebellDeadCleanIcon',
    aliases: ['Kettlebell Dead Clean'],
    poseFamily: 'hinge',
    equipment: ['kettlebell'],
    muscles: ['back'],
  },
  {
    key: 'kettlebell-gorilla-row',
    title: 'Kettlebell Gorilla Row',
    component: 'KettlebellGorillaRowIcon',
    aliases: ['Kettlebell Gorilla Row'],
    poseFamily: 'hinged-pull',
    equipment: ['kettlebell'],
    muscles: ['back'],
  },
  {
    key: 'kettlebell-row',
    title: 'Kettlebell Row',
    component: 'KettlebellRowIcon',
    aliases: ['Kettlebell Row'],
    poseFamily: 'hinged-pull',
    equipment: ['kettlebell'],
    muscles: ['back'],
  },
  {
    key: 'kettlebell-single-arm-swing',
    title: 'Kettlebell Single Arm Swing',
    component: 'KettlebellSingleArmSwingIcon',
    aliases: ['Kettlebell Single Arm Swing'],
    poseFamily: 'ballistic-hinge',
    equipment: ['kettlebell'],
    muscles: ['back'],
  },
  {
    key: 'cable-lat-pulldown',
    title: 'Lat Pulldown',
    component: 'CableLatPulldownIcon',
    aliases: ['Lat Pulldown'],
    poseFamily: 'seated-pulldown',
    equipment: ['cable'],
    muscles: ['back'],
  },
  {
    key: 'cable-straight-arm-pulldown',
    title: 'Straight Arm Pulldown',
    component: 'CableStraightArmPulldownIcon',
    aliases: ['Straight Arm Pulldown'],
    poseFamily: 'standing-pulldown',
    equipment: ['cable'],
    muscles: ['back'],
  },
  {
    key: 'machine-assisted-pull-up',
    title: 'Assisted Pull-up Machine',
    component: 'MachineAssistedPullUpIcon',
    aliases: ['Assisted Pull-up Machine'],
    poseFamily: 'hang-pull',
    equipment: ['machine'],
    muscles: ['back'],
  },
  {
    key: 'machine-back-extension',
    title: 'Back Extension Machine',
    component: 'MachineBackExtensionIcon',
    aliases: ['Back Extension Machine'],
    poseFamily: 'hinge',
    equipment: ['machine'],
    muscles: ['back'],
  },
  {
    key: 'machine-chest-supported-row',
    title: 'Chest Supported Row',
    component: 'MachineChestSupportedRowIcon',
    aliases: ['Chest Supported Row'],
    poseFamily: 'supported-pull',
    equipment: ['machine'],
    muscles: ['back'],
  },
  {
    key: 'machine-reverse-hyper',
    title: 'Reverse Hyper Machine',
    component: 'MachineReverseHyperIcon',
    aliases: ['Reverse Hyper Machine'],
    poseFamily: 'prone-hinge',
    equipment: ['machine'],
    muscles: ['back'],
  },
  {
    key: 'machine-seated-row',
    title: 'Seated Row Machine',
    component: 'MachineSeatedRowIcon',
    aliases: ['Seated Row Machine'],
    poseFamily: 'seated-pull',
    equipment: ['machine'],
    muscles: ['back'],
  },
  {
    key: 'machine-t-bar-row',
    title: 'T-Bar Row Machine',
    component: 'MachineTBarRowIcon',
    aliases: ['T-Bar Row Machine'],
    poseFamily: 'hinged-pull',
    equipment: ['machine'],
    muscles: ['back'],
  },
  {
    key: 'bodyweight-chin-up',
    title: 'Chin-ups',
    component: 'BodyweightChinUpIcon',
    aliases: ['Chin-ups'],
    poseFamily: 'hang-pull',
    equipment: ['bodyweight'],
    muscles: ['back'],
  },
  {
    key: 'bodyweight-dead-hang',
    title: 'Dead Hang',
    component: 'BodyweightDeadHangIcon',
    aliases: ['Dead Hang'],
    poseFamily: 'hang',
    equipment: ['bodyweight'],
    muscles: ['back'],
  },
  {
    key: 'bodyweight-inverted-row',
    title: 'Inverted Rows',
    component: 'BodyweightInvertedRowIcon',
    aliases: ['Inverted Rows'],
    poseFamily: 'supine-pull',
    equipment: ['bodyweight'],
    muscles: ['back'],
  },
  {
    key: 'bodyweight-prone-y-raise',
    title: 'Prone Y-Raises',
    component: 'BodyweightProneYRaiseIcon',
    aliases: ['Prone Y-Raises'],
    poseFamily: 'prone-raise',
    equipment: ['bodyweight'],
    muscles: ['back'],
  },
  {
    key: 'bodyweight-pull-up',
    title: 'Pull-ups',
    component: 'BodyweightPullUpIcon',
    aliases: ['Pull-ups'],
    poseFamily: 'hang-pull',
    equipment: ['bodyweight'],
    muscles: ['back'],
  },
  {
    key: 'club-pullover',
    title: 'Club Pullover',
    component: 'ClubPulloverIcon',
    aliases: ['Club Pullover'],
    poseFamily: 'overhead-arc',
    equipment: ['club'],
    muscles: ['back'],
  },
  {
    key: 'dumbbell-lateral-raise',
    title: 'Lateral Raise',
    component: 'DumbbellLateralRaiseIcon',
    aliases: ['Lateral Raise'],
    poseFamily: 'standing-raise',
    equipment: ['dumbbell'],
    muscles: ['shoulders'],
  },
  {
    key: 'kettlebell-armbar',
    title: 'Kettlebell Armbar',
    component: 'KettlebellArmbarIcon',
    aliases: ['Kettlebell Armbar'],
    poseFamily: 'supine-hold',
    equipment: ['kettlebell'],
    muscles: ['shoulders'],
  },
  {
    key: 'kettlebell-clean',
    title: 'Kettlebell Clean',
    component: 'KettlebellCleanIcon',
    aliases: ['Kettlebell Clean'],
    poseFamily: 'rack-catch',
    equipment: ['kettlebell'],
    muscles: ['shoulders'],
  },
  {
    key: 'kettlebell-clean-and-press',
    title: 'Kettlebell Clean and Press',
    component: 'KettlebellCleanAndPressIcon',
    aliases: ['Kettlebell Clean and Press'],
    poseFamily: 'vertical-press',
    equipment: ['kettlebell'],
    muscles: ['shoulders'],
  },
  {
    key: 'kettlebell-halo',
    title: 'Kettlebell Halo',
    component: 'KettlebellHaloIcon',
    aliases: ['Kettlebell Halo'],
    poseFamily: 'head-circle',
    equipment: ['kettlebell'],
    muscles: ['shoulders'],
  },
  {
    key: 'kettlebell-high-pull',
    title: 'Kettlebell High Pull',
    component: 'KettlebellHighPullIcon',
    aliases: ['Kettlebell High Pull'],
    poseFamily: 'upright-pull',
    equipment: ['kettlebell'],
    muscles: ['shoulders'],
  },
  {
    key: 'kettlebell-press',
    title: 'Kettlebell Press',
    component: 'KettlebellPressIcon',
    aliases: ['Kettlebell Press'],
    poseFamily: 'vertical-press',
    equipment: ['kettlebell'],
    muscles: ['shoulders'],
  },
  {
    key: 'kettlebell-snatch',
    title: 'Kettlebell Snatch',
    component: 'KettlebellSnatchIcon',
    aliases: ['Kettlebell Snatch'],
    poseFamily: 'overhead-lockout',
    equipment: ['kettlebell'],
    muscles: ['shoulders'],
  },
  {
    key: 'cable-face-pull',
    title: 'Cable Face Pull',
    component: 'CableFacePullIcon',
    aliases: ['Cable Face Pull'],
    poseFamily: 'standing-pull',
    equipment: ['cable'],
    muscles: ['shoulders'],
  },
  {
    key: 'cable-reverse-fly',
    title: 'Cable Reverse Fly',
    component: 'CableReverseFlyIcon',
    aliases: ['Cable Reverse Fly'],
    poseFamily: 'standing-fly',
    equipment: ['cable'],
    muscles: ['shoulders'],
  },
  {
    key: 'machine-lateral-raise',
    title: 'Lateral Raise Machine',
    component: 'MachineLateralRaiseIcon',
    aliases: ['Lateral Raise Machine'],
    poseFamily: 'seated-raise',
    equipment: ['machine'],
    muscles: ['shoulders'],
  },
  {
    key: 'machine-rear-delt',
    title: 'Rear Delt Machine',
    component: 'MachineRearDeltIcon',
    aliases: ['Rear Delt Machine'],
    poseFamily: 'seated-fly',
    equipment: ['machine'],
    muscles: ['shoulders'],
  },
  {
    key: 'machine-shoulder-press',
    title: 'Shoulder Press Machine',
    component: 'MachineShoulderPressIcon',
    aliases: ['Shoulder Press Machine'],
    poseFamily: 'seated-press',
    equipment: ['machine'],
    muscles: ['shoulders'],
  },
  {
    key: 'smith-machine-shoulder-press',
    title: 'Smith Machine Shoulder Press',
    component: 'SmithMachineShoulderPressIcon',
    aliases: ['Smith Machine Shoulder Press'],
    poseFamily: 'seated-press',
    equipment: ['machine'],
    muscles: ['shoulders'],
  },
  {
    key: 'bodyweight-handstand-push-up',
    title: 'Handstand Push-ups',
    component: 'BodyweightHandstandPushUpIcon',
    aliases: ['Handstand Push-ups'],
    poseFamily: 'inverted-press',
    equipment: ['bodyweight'],
    muscles: ['shoulders'],
  },
  {
    key: 'bodyweight-pike-hold',
    title: 'Pike Hold',
    component: 'BodyweightPikeHoldIcon',
    aliases: ['Pike Hold'],
    poseFamily: 'pike',
    equipment: ['bodyweight'],
    muscles: ['shoulders'],
  },
  {
    key: 'bodyweight-pike-push-up',
    title: 'Pike Push-ups',
    component: 'BodyweightPikePushUpIcon',
    aliases: ['Pike Push-ups'],
    poseFamily: 'pike',
    equipment: ['bodyweight'],
    muscles: ['shoulders'],
  },
  {
    key: 'bodyweight-shoulder-taps',
    title: 'Shoulder Taps',
    component: 'BodyweightShoulderTapsIcon',
    aliases: ['Shoulder Taps'],
    poseFamily: 'prone-brace',
    equipment: ['bodyweight'],
    muscles: ['shoulders'],
  },
  {
    key: 'club-gama-cast',
    title: 'Club Gama Cast',
    component: 'ClubGamaCastIcon',
    aliases: ['Club Gama Cast'],
    poseFamily: 'club-swing',
    equipment: ['club'],
    muscles: ['shoulders'],
  },
  {
    key: 'club-inside-circle',
    title: 'Club Inside Circle',
    component: 'ClubInsideCircleIcon',
    aliases: ['Club Inside Circle'],
    poseFamily: 'club-circle',
    equipment: ['club'],
    muscles: ['shoulders'],
  },
  {
    key: 'club-mill',
    title: 'Club Mill',
    component: 'ClubMillIcon',
    aliases: ['Club Mill'],
    poseFamily: 'club-mill',
    equipment: ['club'],
    muscles: ['shoulders'],
  },
  {
    key: 'club-outside-circle',
    title: 'Club Outside Circle',
    component: 'ClubOutsideCircleIcon',
    aliases: ['Club Outside Circle'],
    poseFamily: 'club-circle',
    equipment: ['club'],
    muscles: ['shoulders'],
  },
  {
    key: 'club-reverse-mill',
    title: 'Club Reverse Mill',
    component: 'ClubReverseMillIcon',
    aliases: ['Club Reverse Mill'],
    poseFamily: 'club-mill',
    equipment: ['club'],
    muscles: ['shoulders'],
  },
  {
    key: 'club-shield-cast',
    title: 'Club Shield Cast',
    component: 'ClubShieldCastIcon',
    aliases: ['Club Shield Cast'],
    poseFamily: 'club-swing',
    equipment: ['club'],
    muscles: ['shoulders'],
  },
  {
    key: 'club-swipe',
    title: 'Club Swipe',
    component: 'ClubSwipeIcon',
    aliases: ['Club Swipe'],
    poseFamily: 'club-swing',
    equipment: ['club'],
    muscles: ['shoulders'],
  },
  {
    key: 'battle-rope-waves',
    title: 'Battle Rope Waves',
    component: 'BattleRopeWavesIcon',
    aliases: ['Battle Rope Waves'],
    poseFamily: 'rope-slam',
    equipment: ['battle-rope'],
    muscles: ['shoulders'],
  },
  {
    key: 'cable-bicep-curl',
    title: 'Cable Bicep Curl',
    component: 'CableBicepCurlIcon',
    aliases: ['Cable Bicep Curl'],
    poseFamily: 'standing-curl',
    equipment: ['cable'],
    muscles: ['arms'],
  },
  {
    key: 'cable-hammer-curl',
    title: 'Cable Hammer Curl',
    component: 'CableHammerCurlIcon',
    aliases: ['Cable Hammer Curl'],
    poseFamily: 'standing-curl',
    equipment: ['cable'],
    muscles: ['arms'],
  },
  {
    key: 'cable-tricep-extension',
    title: 'Tricep Extension',
    component: 'CableTricepExtensionIcon',
    aliases: ['Tricep Extension'],
    poseFamily: 'standing-pushdown',
    equipment: ['cable'],
    muscles: ['arms'],
  },
  {
    key: 'machine-bicep-curl',
    title: 'Bicep Curl Machine',
    component: 'MachineBicepCurlIcon',
    aliases: ['Bicep Curl Machine'],
    poseFamily: 'seated-curl',
    equipment: ['machine'],
    muscles: ['arms'],
  },
  {
    key: 'machine-preacher-curl',
    title: 'Preacher Curl Machine',
    component: 'MachinePreacherCurlIcon',
    aliases: ['Preacher Curl Machine'],
    poseFamily: 'seated-curl',
    equipment: ['machine'],
    muscles: ['arms'],
  },
  {
    key: 'machine-tricep-dip',
    title: 'Tricep Dip Machine',
    component: 'MachineTricepDipIcon',
    aliases: ['Tricep Dip Machine'],
    poseFamily: 'seated-press',
    equipment: ['machine'],
    muscles: ['arms'],
  },
  {
    key: 'machine-tricep-extension',
    title: 'Tricep Extension Machine',
    component: 'MachineTricepExtensionIcon',
    aliases: ['Tricep Extension Machine'],
    poseFamily: 'seated-extension',
    equipment: ['machine'],
    muscles: ['arms'],
  },
  {
    key: 'bodyweight-bench-dips',
    title: 'Bench Dips',
    component: 'BodyweightBenchDipsIcon',
    aliases: ['Bench Dips'],
    poseFamily: 'support-press',
    equipment: ['bodyweight'],
    muscles: ['arms'],
  },
  {
    key: 'barbell-calf-raise',
    title: 'Barbell Calf Raises',
    component: 'BarbellCalfRaiseIcon',
    aliases: ['Barbell Calf Raises'],
    poseFamily: 'standing-raise',
    equipment: ['barbell'],
    muscles: ['legs'],
  },
  {
    key: 'barbell-good-morning',
    title: 'Barbell Good Mornings',
    component: 'BarbellGoodMorningIcon',
    aliases: ['Barbell Good Mornings'],
    poseFamily: 'hinge',
    equipment: ['barbell'],
    muscles: ['legs'],
  },
  {
    key: 'barbell-hip-thrust',
    title: 'Barbell Hip Thrust',
    component: 'BarbellHipThrustIcon',
    aliases: ['Barbell Hip Thrust'],
    poseFamily: 'supine-bridge',
    equipment: ['barbell'],
    muscles: ['legs'],
  },
  {
    key: 'barbell-lunge',
    title: 'Barbell Lunges',
    component: 'BarbellLungeIcon',
    aliases: ['Barbell Lunges'],
    poseFamily: 'lunge',
    equipment: ['barbell'],
    muscles: ['legs'],
  },
  {
    key: 'barbell-romanian-deadlift',
    title: 'Barbell Romanian Deadlift',
    component: 'BarbellRomanianDeadliftIcon',
    aliases: ['Barbell Romanian Deadlift'],
    poseFamily: 'hinge',
    equipment: ['barbell'],
    muscles: ['legs'],
  },
  {
    key: 'barbell-front-squat',
    title: 'Front Squat',
    component: 'BarbellFrontSquatIcon',
    aliases: ['Front Squat'],
    poseFamily: 'squat',
    equipment: ['barbell'],
    muscles: ['legs'],
  },
  {
    key: 'barbell-sumo-deadlift',
    title: 'Sumo Deadlift',
    component: 'BarbellSumoDeadliftIcon',
    aliases: ['Sumo Deadlift'],
    poseFamily: 'hinge',
    equipment: ['barbell'],
    muscles: ['legs'],
  },
  {
    key: 'dumbbell-bulgarian-split-squat',
    title: 'Dumbbell Bulgarian Split Squat',
    component: 'DumbbellBulgarianSplitSquatIcon',
    aliases: ['Dumbbell Bulgarian Split Squat'],
    poseFamily: 'split-squat',
    equipment: ['dumbbell'],
    muscles: ['legs'],
  },
  {
    key: 'dumbbell-calf-raise',
    title: 'Dumbbell Calf Raises',
    component: 'DumbbellCalfRaiseIcon',
    aliases: ['Dumbbell Calf Raises'],
    poseFamily: 'standing-raise',
    equipment: ['dumbbell'],
    muscles: ['legs'],
  },
  {
    key: 'dumbbell-goblet-squat',
    title: 'Dumbbell Goblet Squat',
    component: 'DumbbellGobletSquatIcon',
    aliases: ['Dumbbell Goblet Squat'],
    poseFamily: 'goblet-squat',
    equipment: ['dumbbell'],
    muscles: ['legs'],
  },
  {
    key: 'dumbbell-hip-thrust',
    title: 'Dumbbell Hip Thrust',
    component: 'DumbbellHipThrustIcon',
    aliases: ['Dumbbell Hip Thrust'],
    poseFamily: 'supine-bridge',
    equipment: ['dumbbell'],
    muscles: ['legs'],
  },
  {
    key: 'dumbbell-lunge',
    title: 'Dumbbell Lunges',
    component: 'DumbbellLungeIcon',
    aliases: ['Dumbbell Lunges'],
    poseFamily: 'lunge',
    equipment: ['dumbbell'],
    muscles: ['legs'],
  },
  {
    key: 'dumbbell-romanian-deadlift',
    title: 'Dumbbell Romanian Deadlift',
    component: 'DumbbellRomanianDeadliftIcon',
    aliases: ['Dumbbell Romanian Deadlift'],
    poseFamily: 'hinge',
    equipment: ['dumbbell'],
    muscles: ['legs'],
  },
  {
    key: 'dumbbell-single-leg-deadlift',
    title: 'Dumbbell Single Leg Deadlift',
    component: 'DumbbellSingleLegDeadliftIcon',
    aliases: ['Dumbbell Single Leg Deadlift'],
    poseFamily: 'single-leg-hinge',
    equipment: ['dumbbell'],
    muscles: ['legs'],
  },
  {
    key: 'dumbbell-step-up',
    title: 'Dumbbell Step-ups',
    component: 'DumbbellStepUpIcon',
    aliases: ['Dumbbell Step-ups'],
    poseFamily: 'step-up',
    equipment: ['dumbbell'],
    muscles: ['legs'],
  },
  {
    key: 'dumbbell-sumo-squat',
    title: 'Dumbbell Sumo Squat',
    component: 'DumbbellSumoSquatIcon',
    aliases: ['Dumbbell Sumo Squat'],
    poseFamily: 'squat',
    equipment: ['dumbbell'],
    muscles: ['legs'],
  },
  {
    key: 'kettlebell-single-leg-deadlift',
    title: 'Kettlebell Single Leg Deadlift',
    component: 'KettlebellSingleLegDeadliftIcon',
    aliases: ['Kettlebell Single Leg Deadlift'],
    poseFamily: 'single-leg-hinge',
    equipment: ['kettlebell'],
    muscles: ['legs'],
  },
  {
    key: 'kettlebell-thruster',
    title: 'Kettlebell Thruster',
    component: 'KettlebellThrusterIcon',
    aliases: ['Kettlebell Thruster'],
    poseFamily: 'squat-press',
    equipment: ['kettlebell'],
    muscles: ['legs'],
  },
  {
    key: 'cable-kickback',
    title: 'Cable Kickbacks',
    component: 'CableKickbackIcon',
    aliases: ['Cable Kickbacks'],
    poseFamily: 'standing-kickback',
    equipment: ['cable'],
    muscles: ['legs'],
  },
  {
    key: 'cable-pull-through',
    title: 'Cable Pull-Through',
    component: 'CablePullThroughIcon',
    aliases: ['Cable Pull-Through'],
    poseFamily: 'hinge',
    equipment: ['cable'],
    muscles: ['legs'],
  },
  {
    key: 'cable-romanian-deadlift',
    title: 'Cable Romanian Deadlift',
    component: 'CableRomanianDeadliftIcon',
    aliases: ['Cable Romanian Deadlift'],
    poseFamily: 'hinge',
    equipment: ['cable'],
    muscles: ['legs'],
  },
  {
    key: 'machine-belt-squat',
    title: 'Belt Squat Machine',
    component: 'MachineBeltSquatIcon',
    aliases: ['Belt Squat Machine'],
    poseFamily: 'squat',
    equipment: ['machine'],
    muscles: ['legs'],
  },
  {
    key: 'machine-donkey-calf-raise',
    title: 'Donkey Calf Raise Machine',
    component: 'MachineDonkeyCalfRaiseIcon',
    aliases: ['Donkey Calf Raise Machine'],
    poseFamily: 'hinged-raise',
    equipment: ['machine'],
    muscles: ['legs'],
  },
  {
    key: 'machine-glute-drive',
    title: 'Glute Drive Machine',
    component: 'MachineGluteDriveIcon',
    aliases: ['Glute Drive Machine'],
    poseFamily: 'supine-bridge',
    equipment: ['machine'],
    muscles: ['legs'],
  },
  {
    key: 'machine-glute-kickback',
    title: 'Glute Kickback Machine',
    component: 'MachineGluteKickbackIcon',
    aliases: ['Glute Kickback Machine'],
    poseFamily: 'standing-kickback',
    equipment: ['machine'],
    muscles: ['legs'],
  },
  {
    key: 'machine-hack-squat',
    title: 'Hack Squat Machine',
    component: 'MachineHackSquatIcon',
    aliases: ['Hack Squat Machine'],
    poseFamily: 'sled-squat',
    equipment: ['machine'],
    muscles: ['legs'],
  },
  {
    key: 'machine-hip-abduction',
    title: 'Hip Abduction Machine',
    component: 'MachineHipAbductionIcon',
    aliases: ['Hip Abduction Machine'],
    poseFamily: 'seated-legs-open',
    equipment: ['machine'],
    muscles: ['legs'],
  },
  {
    key: 'machine-hip-adduction',
    title: 'Hip Adduction Machine',
    component: 'MachineHipAdductionIcon',
    aliases: ['Hip Adduction Machine'],
    poseFamily: 'seated-legs-closed',
    equipment: ['machine'],
    muscles: ['legs'],
  },
  {
    key: 'machine-hip-thrust',
    title: 'Hip Thrust Machine',
    component: 'MachineHipThrustIcon',
    aliases: ['Hip Thrust Machine'],
    poseFamily: 'supine-bridge',
    equipment: ['machine'],
    muscles: ['legs'],
  },
  {
    key: 'machine-leg-curl',
    title: 'Leg Curl',
    component: 'MachineLegCurlIcon',
    aliases: ['Leg Curl'],
    poseFamily: 'seated-curl-leg',
    equipment: ['machine'],
    muscles: ['legs'],
  },
  {
    key: 'machine-leg-extension',
    title: 'Leg Extension',
    component: 'MachineLegExtensionIcon',
    aliases: ['Leg Extension'],
    poseFamily: 'seated-extension-leg',
    equipment: ['machine'],
    muscles: ['legs'],
  },
  {
    key: 'machine-leg-press',
    title: 'Leg Press',
    component: 'MachineLegPressIcon',
    aliases: ['Leg Press'],
    poseFamily: 'seated-leg-press',
    equipment: ['machine'],
    muscles: ['legs'],
  },
  {
    key: 'machine-leg-press-calf-raise',
    title: 'Leg Press Calf Raise',
    component: 'MachineLegPressCalfRaiseIcon',
    aliases: ['Leg Press Calf Raise'],
    poseFamily: 'seated-leg-press',
    equipment: ['machine'],
    muscles: ['legs'],
  },
  {
    key: 'machine-lying-leg-curl',
    title: 'Lying Leg Curl',
    component: 'MachineLyingLegCurlIcon',
    aliases: ['Lying Leg Curl'],
    poseFamily: 'prone-curl-leg',
    equipment: ['machine'],
    muscles: ['legs'],
  },
  {
    key: 'machine-nordic-curl',
    title: 'Nordic Curl Machine',
    component: 'MachineNordicCurlIcon',
    aliases: ['Nordic Curl Machine'],
    poseFamily: 'kneeling-lower',
    equipment: ['machine'],
    muscles: ['legs'],
  },
  {
    key: 'machine-pendulum-squat',
    title: 'Pendulum Squat',
    component: 'MachinePendulumSquatIcon',
    aliases: ['Pendulum Squat'],
    poseFamily: 'sled-squat',
    equipment: ['machine'],
    muscles: ['legs'],
  },
  {
    key: 'machine-reverse-hack-squat',
    title: 'Reverse Hack Squat',
    component: 'MachineReverseHackSquatIcon',
    aliases: ['Reverse Hack Squat'],
    poseFamily: 'sled-squat',
    equipment: ['machine'],
    muscles: ['legs'],
  },
  {
    key: 'machine-seated-calf-raise',
    title: 'Seated Calf Raise',
    component: 'MachineSeatedCalfRaiseIcon',
    aliases: ['Seated Calf Raise'],
    poseFamily: 'seated-raise',
    equipment: ['machine'],
    muscles: ['legs'],
  },
  {
    key: 'machine-seated-leg-curl',
    title: 'Seated Leg Curl',
    component: 'MachineSeatedLegCurlIcon',
    aliases: ['Seated Leg Curl'],
    poseFamily: 'seated-curl-leg',
    equipment: ['machine'],
    muscles: ['legs'],
  },
  {
    key: 'machine-sissy-squat',
    title: 'Sissy Squat Machine',
    component: 'MachineSissySquatIcon',
    aliases: ['Sissy Squat Machine'],
    poseFamily: 'lean-back-squat',
    equipment: ['machine'],
    muscles: ['legs'],
  },
  {
    key: 'smith-machine-lunge',
    title: 'Smith Machine Lunges',
    component: 'SmithMachineLungeIcon',
    aliases: ['Smith Machine Lunges'],
    poseFamily: 'lunge',
    equipment: ['machine'],
    muscles: ['legs'],
  },
  {
    key: 'smith-machine-romanian-deadlift',
    title: 'Smith Machine Romanian Deadlift',
    component: 'SmithMachineRomanianDeadliftIcon',
    aliases: ['Smith Machine Romanian Deadlift'],
    poseFamily: 'hinge',
    equipment: ['machine'],
    muscles: ['legs'],
  },
  {
    key: 'smith-machine-squat',
    title: 'Smith Machine Squat',
    component: 'SmithMachineSquatIcon',
    aliases: ['Smith Machine Squat'],
    poseFamily: 'squat',
    equipment: ['machine'],
    muscles: ['legs'],
  },
  {
    key: 'machine-standing-calf-raise',
    title: 'Standing Calf Raise Machine',
    component: 'MachineStandingCalfRaiseIcon',
    aliases: ['Standing Calf Raise Machine'],
    poseFamily: 'standing-raise',
    equipment: ['machine'],
    muscles: ['legs'],
  },
  {
    key: 'machine-standing-leg-curl',
    title: 'Standing Leg Curl',
    component: 'MachineStandingLegCurlIcon',
    aliases: ['Standing Leg Curl'],
    poseFamily: 'standing-curl-leg',
    equipment: ['machine'],
    muscles: ['legs'],
  },
  {
    key: 'machine-v-squat',
    title: 'V-Squat Machine',
    component: 'MachineVSquatIcon',
    aliases: ['V-Squat Machine'],
    poseFamily: 'sled-squat',
    equipment: ['machine'],
    muscles: ['legs'],
  },
  {
    key: 'machine-vertical-leg-press',
    title: 'Vertical Leg Press',
    component: 'MachineVerticalLegPressIcon',
    aliases: ['Vertical Leg Press'],
    poseFamily: 'supine-leg-press',
    equipment: ['machine'],
    muscles: ['legs'],
  },
  {
    key: 'bodyweight-squat',
    title: 'Bodyweight Squat',
    component: 'BodyweightSquatIcon',
    aliases: ['Bodyweight Squat'],
    poseFamily: 'squat',
    equipment: ['bodyweight'],
    muscles: ['legs'],
  },
  {
    key: 'bodyweight-bulgarian-split-squat',
    title: 'Bulgarian Split Squat',
    component: 'BodyweightBulgarianSplitSquatIcon',
    aliases: ['Bulgarian Split Squat'],
    poseFamily: 'split-squat',
    equipment: ['bodyweight'],
    muscles: ['legs'],
  },
  {
    key: 'bodyweight-burpee',
    title: 'Burpees',
    component: 'BodyweightBurpeeIcon',
    aliases: ['Burpees'],
    poseFamily: 'jump',
    equipment: ['bodyweight'],
    muscles: ['legs'],
  },
  {
    key: 'bodyweight-butt-kicks',
    title: 'Butt Kicks',
    component: 'BodyweightButtKicksIcon',
    aliases: ['Butt Kicks'],
    poseFamily: 'run',
    equipment: ['bodyweight'],
    muscles: ['legs'],
  },
  {
    key: 'bodyweight-calf-raise',
    title: 'Calf Raises',
    component: 'BodyweightCalfRaiseIcon',
    aliases: ['Calf Raises'],
    poseFamily: 'standing-raise',
    equipment: ['bodyweight'],
    muscles: ['legs'],
  },
  {
    key: 'bodyweight-donkey-kick',
    title: 'Donkey Kicks',
    component: 'BodyweightDonkeyKickIcon',
    aliases: ['Donkey Kicks'],
    poseFamily: 'quadruped-kick',
    equipment: ['bodyweight'],
    muscles: ['legs'],
  },
  {
    key: 'bodyweight-glute-bridge-hold',
    title: 'Glute Bridge Hold',
    component: 'BodyweightGluteBridgeHoldIcon',
    aliases: ['Glute Bridge Hold'],
    poseFamily: 'supine-bridge',
    equipment: ['bodyweight'],
    muscles: ['legs'],
  },
  {
    key: 'bodyweight-glute-bridge',
    title: 'Glute Bridges',
    component: 'BodyweightGluteBridgeIcon',
    aliases: ['Glute Bridges'],
    poseFamily: 'supine-bridge',
    equipment: ['bodyweight'],
    muscles: ['legs'],
  },
  {
    key: 'bodyweight-high-knees',
    title: 'High Knees',
    component: 'BodyweightHighKneesIcon',
    aliases: ['High Knees'],
    poseFamily: 'run',
    equipment: ['bodyweight'],
    muscles: ['legs'],
  },
  {
    key: 'bodyweight-jump-lunge',
    title: 'Jump Lunges',
    component: 'BodyweightJumpLungeIcon',
    aliases: ['Jump Lunges'],
    poseFamily: 'jump-lunge',
    equipment: ['bodyweight'],
    muscles: ['legs'],
  },
  {
    key: 'bodyweight-jump-rope',
    title: 'Jump Rope',
    component: 'BodyweightJumpRopeIcon',
    aliases: ['Jump Rope'],
    poseFamily: 'jump-rope',
    equipment: ['bodyweight'],
    muscles: ['legs'],
  },
  {
    key: 'bodyweight-jump-squat',
    title: 'Jump Squats',
    component: 'BodyweightJumpSquatIcon',
    aliases: ['Jump Squats'],
    poseFamily: 'jump',
    equipment: ['bodyweight'],
    muscles: ['legs'],
  },
  {
    key: 'bodyweight-jumping-jacks',
    title: 'Jumping Jacks',
    component: 'BodyweightJumpingJacksIcon',
    aliases: ['Jumping Jacks'],
    poseFamily: 'star-jump',
    equipment: ['bodyweight'],
    muscles: ['legs'],
  },
  {
    key: 'bodyweight-lunge',
    title: 'Lunges',
    component: 'BodyweightLungeIcon',
    aliases: ['Lunges'],
    poseFamily: 'lunge',
    equipment: ['bodyweight'],
    muscles: ['legs'],
  },
  {
    key: 'bodyweight-pistol-squat',
    title: 'Pistol Squats',
    component: 'BodyweightPistolSquatIcon',
    aliases: ['Pistol Squats'],
    poseFamily: 'single-leg-squat',
    equipment: ['bodyweight'],
    muscles: ['legs'],
  },
  {
    key: 'bodyweight-reverse-lunge',
    title: 'Reverse Lunges',
    component: 'BodyweightReverseLungeIcon',
    aliases: ['Reverse Lunges'],
    poseFamily: 'lunge',
    equipment: ['bodyweight'],
    muscles: ['legs'],
  },
  {
    key: 'bodyweight-single-leg-glute-bridge',
    title: 'Single Leg Glute Bridge',
    component: 'BodyweightSingleLegGluteBridgeIcon',
    aliases: ['Single Leg Glute Bridge'],
    poseFamily: 'supine-bridge',
    equipment: ['bodyweight'],
    muscles: ['legs'],
  },
  {
    key: 'bodyweight-sprawl',
    title: 'Sprawls',
    component: 'BodyweightSprawlIcon',
    aliases: ['Sprawls'],
    poseFamily: 'prone-thrust',
    equipment: ['bodyweight'],
    muscles: ['legs'],
  },
  {
    key: 'bodyweight-squat-thrust',
    title: 'Squat Thrusts',
    component: 'BodyweightSquatThrustIcon',
    aliases: ['Squat Thrusts'],
    poseFamily: 'prone-thrust',
    equipment: ['bodyweight'],
    muscles: ['legs'],
  },
  {
    key: 'bodyweight-step-up',
    title: 'Step-ups',
    component: 'BodyweightStepUpIcon',
    aliases: ['Step-ups'],
    poseFamily: 'step-up',
    equipment: ['bodyweight'],
    muscles: ['legs'],
  },
  {
    key: 'bodyweight-tuck-jump',
    title: 'Tuck Jumps',
    component: 'BodyweightTuckJumpIcon',
    aliases: ['Tuck Jumps'],
    poseFamily: 'jump',
    equipment: ['bodyweight'],
    muscles: ['legs'],
  },
  {
    key: 'bodyweight-walking-lunge',
    title: 'Walking Lunges',
    component: 'BodyweightWalkingLungeIcon',
    aliases: ['Walking Lunges'],
    poseFamily: 'lunge',
    equipment: ['bodyweight'],
    muscles: ['legs'],
  },
  {
    key: 'bodyweight-wall-sit',
    title: 'Wall Sit',
    component: 'BodyweightWallSitIcon',
    aliases: ['Wall Sit'],
    poseFamily: 'wall-sit',
    equipment: ['bodyweight'],
    muscles: ['legs'],
  },
  {
    key: 'kettlebell-figure-8',
    title: 'Kettlebell Figure 8',
    component: 'KettlebellFigure8Icon',
    aliases: ['Kettlebell Figure 8'],
    poseFamily: 'rotation',
    equipment: ['kettlebell'],
    muscles: ['core'],
  },
  {
    key: 'kettlebell-windmill',
    title: 'Kettlebell Windmill',
    component: 'KettlebellWindmillIcon',
    aliases: ['Kettlebell Windmill'],
    poseFamily: 'windmill',
    equipment: ['kettlebell'],
    muscles: ['core'],
  },
  {
    key: 'dumbbell-weighted-plank',
    title: 'Weighted Plank',
    component: 'DumbbellWeightedPlankIcon',
    aliases: ['Weighted Plank'],
    poseFamily: 'prone-brace',
    equipment: ['dumbbell'],
    muscles: ['core'],
  },
  {
    key: 'cable-crunch',
    title: 'Cable Crunch',
    component: 'CableCrunchIcon',
    aliases: ['Cable Crunch'],
    poseFamily: 'kneeling-crunch',
    equipment: ['cable'],
    muscles: ['core'],
  },
  {
    key: 'cable-woodchop',
    title: 'Cable Woodchop',
    component: 'CableWoodchopIcon',
    aliases: ['Cable Woodchop'],
    poseFamily: 'rotation',
    equipment: ['cable'],
    muscles: ['core'],
  },
  {
    key: 'bodyweight-bear-crawl',
    title: 'Bear Crawl',
    component: 'BodyweightBearCrawlIcon',
    aliases: ['Bear Crawl'],
    poseFamily: 'quadruped',
    equipment: ['bodyweight'],
    muscles: ['core'],
  },
  {
    key: 'bodyweight-bicycle-crunch',
    title: 'Bicycle Crunches',
    component: 'BodyweightBicycleCrunchIcon',
    aliases: ['Bicycle Crunches'],
    poseFamily: 'supine-crunch',
    equipment: ['bodyweight'],
    muscles: ['core'],
  },
  {
    key: 'bodyweight-bird-dog',
    title: 'Bird Dog',
    component: 'BodyweightBirdDogIcon',
    aliases: ['Bird Dog'],
    poseFamily: 'quadruped-reach',
    equipment: ['bodyweight'],
    muscles: ['core'],
  },
  {
    key: 'bodyweight-get-up',
    title: 'Bodyweight Get-up',
    component: 'BodyweightGetUpIcon',
    aliases: ['Bodyweight Get-up'],
    poseFamily: 'ground-to-standing',
    equipment: ['bodyweight'],
    muscles: ['core'],
  },
  {
    key: 'bodyweight-crunch',
    title: 'Crunches',
    component: 'BodyweightCrunchIcon',
    aliases: ['Crunches'],
    poseFamily: 'supine-crunch',
    equipment: ['bodyweight'],
    muscles: ['core'],
  },
  {
    key: 'bodyweight-dead-bug',
    title: 'Dead Bug',
    component: 'BodyweightDeadBugIcon',
    aliases: ['Dead Bug'],
    poseFamily: 'supine-reach',
    equipment: ['bodyweight'],
    muscles: ['core'],
  },
  {
    key: 'bodyweight-flutter-kicks',
    title: 'Flutter Kicks',
    component: 'BodyweightFlutterKicksIcon',
    aliases: ['Flutter Kicks'],
    poseFamily: 'supine-kick',
    equipment: ['bodyweight'],
    muscles: ['core'],
  },
  {
    key: 'bodyweight-hollow-body-hold',
    title: 'Hollow Body Hold',
    component: 'BodyweightHollowBodyHoldIcon',
    aliases: ['Hollow Body Hold'],
    poseFamily: 'supine-hollow',
    equipment: ['bodyweight'],
    muscles: ['core'],
  },
  {
    key: 'bodyweight-inchworm',
    title: 'Inchworms',
    component: 'BodyweightInchwormIcon',
    aliases: ['Inchworms'],
    poseFamily: 'pike-walk',
    equipment: ['bodyweight'],
    muscles: ['core'],
  },
  {
    key: 'bodyweight-l-sit',
    title: 'L-Sit',
    component: 'BodyweightLSitIcon',
    aliases: ['L-Sit'],
    poseFamily: 'support-hold',
    equipment: ['bodyweight'],
    muscles: ['core'],
  },
  {
    key: 'bodyweight-leg-raise',
    title: 'Leg Raises',
    component: 'BodyweightLegRaiseIcon',
    aliases: ['Leg Raises'],
    poseFamily: 'supine-kick',
    equipment: ['bodyweight'],
    muscles: ['core'],
  },
  {
    key: 'bodyweight-mountain-climber',
    title: 'Mountain Climbers',
    component: 'BodyweightMountainClimberIcon',
    aliases: ['Mountain Climbers'],
    poseFamily: 'prone-drive',
    equipment: ['bodyweight'],
    muscles: ['core'],
  },
  {
    key: 'bodyweight-plank-to-pike',
    title: 'Plank to Pike',
    component: 'BodyweightPlankToPikeIcon',
    aliases: ['Plank to Pike'],
    poseFamily: 'pike',
    equipment: ['bodyweight'],
    muscles: ['core'],
  },
  {
    key: 'bodyweight-reverse-crunch',
    title: 'Reverse Crunches',
    component: 'BodyweightReverseCrunchIcon',
    aliases: ['Reverse Crunches'],
    poseFamily: 'supine-crunch',
    equipment: ['bodyweight'],
    muscles: ['core'],
  },
  {
    key: 'bodyweight-russian-twist',
    title: 'Russian Twists',
    component: 'BodyweightRussianTwistIcon',
    aliases: ['Russian Twists'],
    poseFamily: 'seated-twist',
    equipment: ['bodyweight'],
    muscles: ['core'],
  },
  {
    key: 'bodyweight-side-plank',
    title: 'Side Plank',
    component: 'BodyweightSidePlankIcon',
    aliases: ['Side Plank'],
    poseFamily: 'side-brace',
    equipment: ['bodyweight'],
    muscles: ['core'],
  },
  {
    key: 'bodyweight-sit-up',
    title: 'Sit-ups',
    component: 'BodyweightSitUpIcon',
    aliases: ['Sit-ups'],
    poseFamily: 'supine-crunch',
    equipment: ['bodyweight'],
    muscles: ['core'],
  },
  {
    key: 'bodyweight-superman',
    title: 'Superman',
    component: 'BodyweightSupermanIcon',
    aliases: ['Superman'],
    poseFamily: 'prone-raise',
    equipment: ['bodyweight'],
    muscles: ['core'],
  },
  {
    key: 'bodyweight-toe-touch',
    title: 'Toe Touches',
    component: 'BodyweightToeTouchIcon',
    aliases: ['Toe Touches'],
    poseFamily: 'supine-reach',
    equipment: ['bodyweight'],
    muscles: ['core'],
  },
  {
    key: 'bodyweight-v-up',
    title: 'V-ups',
    component: 'BodyweightVUpIcon',
    aliases: ['V-ups'],
    poseFamily: 'supine-fold',
    equipment: ['bodyweight'],
    muscles: ['core'],
  },
  {
    key: 'club-pendulum',
    title: 'Club Pendulum',
    component: 'ClubPendulumIcon',
    aliases: ['Club Pendulum'],
    poseFamily: 'club-swing',
    equipment: ['club'],
    muscles: ['core'],
  },
] as const satisfies ReadonlyArray<ExerciseIconManifestEntry>
