name: Release

on:
  push:
    branches: [main]

permissions: {}

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Conventional changelog
        uses: TriPSs/conventional-changelog-action@91be4f3188da74fe85de9caffcebc80b26d43b5b # v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tag-prefix: 'v'
          output-file: 'CHANGELOG.md'
          skip-version-file: 'false'
          skip-commit: 'false'
          git-message: 'chore(release): {version}'
          git-user-name: 'github-actions[bot]'
          git-user-email: 'github-actions[bot]@users.noreply.github.com'
